INSERT INTO EMPLOYEE (IS_ADMIN, ID_EMPLOYE, NAME, PASSWORD) VALUES ('1', default, 'admin', 'admin');
INSERT INTO EMPLOYEE (IS_ADMIN, ID_EMPLOYE, NAME, PASSWORD) VALUES ('0', default, 'paco', 'paco');
INSERT INTO EMPLOYEE (IS_ADMIN, ID_EMPLOYE, NAME, PASSWORD) VALUES ('0', default, 'lucas', 'lucas');
INSERT INTO EMPLOYEE (IS_ADMIN, ID_EMPLOYE, NAME, PASSWORD) VALUES ('0', default, 'lola', 'lola');