INSERT INTO EMPLOYEE (IS_ADMIN, ID_EMPLOYE, NAME, PASSWORD) VALUES ('1', default, 'admin', 'admin');
INSERT INTO EMPLOYEE (IS_ADMIN, ID_EMPLOYE, NAME, PASSWORD) VALUES ('0', default, 'paco', 'paco');
INSERT INTO EMPLOYEE (IS_ADMIN, ID_EMPLOYE, NAME, PASSWORD) VALUES ('0', default, 'lucas', 'lucas');
INSERT INTO EMPLOYEE (IS_ADMIN, ID_EMPLOYE, NAME, PASSWORD) VALUES ('0', default, 'lola', 'lola');


INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-01', 'NO TENGO RATÓN ME LO ROBARON', 'NO TENGO RATÓN', 'HARDWARE');

INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-01', 'NECESITO UN PAQUETE OFIMÁTICO', 'NECESITO OFFICE 365', 'SOFTWARE');

INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-01', 'TENGO UN PANTALLAZO AZUL AL ENCENDER EL ORDENADOR', 'PANTALLAZO AZUL', 'HARDWARE');

INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-01', 'NECESITO VACACIONES PARA ESTAR MÁS DESCANSADO', 'NECESITO VACACIONES', 'VIEN ESTAR');


