INSERT INTO EMPLOYEE (IS_ADMIN, ID_EMPLOYE, NAME, PASSWORD) VALUES ('1', default, 'admin', 'admin');
INSERT INTO EMPLOYEE (IS_ADMIN, ID_EMPLOYE, NAME, PASSWORD) VALUES ('0', default, 'paco', 'paco');
INSERT INTO EMPLOYEE (IS_ADMIN, ID_EMPLOYE, NAME, PASSWORD) VALUES ('0', default, 'lucas', 'lucas');
INSERT INTO EMPLOYEE (IS_ADMIN, ID_EMPLOYE, NAME, PASSWORD) VALUES ('0', default, 'lola', 'lola');


INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-01', 'NO TENGO RATÓN ME LO ROBARON', 'EL LOGIN DE LA APP NO ME FUNCIONA', 'HARDWARE');

INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-01', '400 BAD REQUEST', ' POSTMAN FALLA 400 BAD REQUEST', 'SOFTWARE');

INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-01', 'TENGO UN PANTALLAZO AZUL AL ENCENDER EL ORDENADOR', 'PANTALLAZO AZUL', 'HARDWARE');

INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-01', 'NECESITO VACACIONES PARA ESTAR MÁS DESCANSADO', 'NECESITO VACACIONES', 'HARDWARE');


INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-02', 'MI TECLADO NO FUNCIONA', '404 NOT FOUND', 'HARDWARE');

INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-03', 'MI PANTALLA ESTÁ ROTA', 'PANTALLA ROTA', 'HARDWARE');

INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-04', 'MI ORDENADOR NO SE ENCIENDE', 'ORDENADOR APAGADO', 'HARDWARE');

INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-05', 'NECESITO UN NUEVO PROCESADOR DE TEXTOS', 'NECESITO WORD', 'SOFTWARE');

INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-06', 'MI WIFI NO FUNCIONA', 'WIFI DESCONECTADO', 'HARDWARE');

INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-07', 'NECESITO UN NUEVO PROGRAMA DE DISEÑO', 'NECESITO PHOTOSHOP', 'SOFTWARE');

INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-08', 'MI IMPRESORA NO IMPRIME', 'IMPRESORA ROTA', 'HARDWARE');

INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-09', 'MI RATÓN NO SE MUEVE', 'RATÓN ROTO', 'HARDWARE');

INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-10', 'MI ORDENADOR HACE MUCHO RUIDO', 'ORDENADOR RUIDOSO', 'HARDWARE');

INSERT INTO INCIDENCE (ID_INCIDENCE, DATE_INCIDENCE, DESPRIPTION_INCIDENCE, TITLE_INCIDENCE, TYPE_INCIDENCE) 
VALUES (default, '2024-01-11', 'NECESITO UN NUEVO PROGRAMA DE HOJAS DE CÁLCULO', 'NECESITO EXCEL', 'SOFTWARE');
